#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════
# IQcadence — Build Script
# Concatenates js/src/*.js into js/app.js in dependency order.
# Usage: bash build.sh
# ═══════════════════════════════════════════════════════════════

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
SRC="$SCRIPT_DIR/js/src"
OUT="$SCRIPT_DIR/js/app.js"

FILES=(
  state.js
  utils.js
  supabase.js
  auth.js
  scoring.js
  nav.js
  homebase.js
  alerts.js
  customers.js
  detail.js
  settings.js
  reports.js
  automations.js
  segments.js
  trends.js
  csm.js
  calendar.js
  audit.js
  csv.js
  admin.js
  main.js
)

# Header
echo "/* ============================================================" > "$OUT"
echo "   IQcadence — CS Health Score — app.js" >> "$OUT"
echo "   Built from js/src/ — DO NOT EDIT THIS FILE DIRECTLY" >> "$OUT"
echo "   ============================================================ */" >> "$OUT"
echo "" >> "$OUT"

for f in "${FILES[@]}"; do
  if [ ! -f "$SRC/$f" ]; then
    echo "ERROR: Missing $SRC/$f" >&2
    exit 1
  fi
  echo "" >> "$OUT"
  cat "$SRC/$f" >> "$OUT"
  echo "" >> "$OUT"
done

echo "Built $OUT ($(wc -l < "$OUT") lines)"
