#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════
# IQcadence — Build Script
# Builds core bundle (js/app.js) + lazy chunks (js/chunks/*.js)
# Usage: bash build.sh
# ═══════════════════════════════════════════════════════════════

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
SRC="$SCRIPT_DIR/js/src"
OUT="$SCRIPT_DIR/js/app.js"
CHUNKS_DIR="$SCRIPT_DIR/js/chunks"

# ─── Core bundle (always loaded) ─────────────────────────────
CORE_FILES=(
  state.js
  utils.js
  guides.js
  walkthrough.js
  supabase.js
  auth.js
  scoring.js
  nav.js
  homebase.js
  alerts.js
  customers.js
  detail.js
  settings.js
  main.js
)

# ─── Lazy chunks (loaded on-demand per route) ────────────────
# Format: "chunk_name:source_file"
CHUNK_FILES=(
  "forecast:forecast.js"
  "calendar:calendar.js"
  "trends:trends.js"
  "reports:reports.js"
  "automations:automations.js"
  "segments:segments.js"
  "csm:csm.js"
  "audit:audit.js"
  "csv:csv.js"
  "admin:admin.js"
)

# ─── Build core bundle ───────────────────────────────────────
echo "/* ============================================================" > "$OUT"
echo "   IQcadence — CS Health Score — app.js (core bundle)" >> "$OUT"
echo "   Built from js/src/ — DO NOT EDIT THIS FILE DIRECTLY" >> "$OUT"
echo "   ============================================================ */" >> "$OUT"
echo "" >> "$OUT"

for f in "${CORE_FILES[@]}"; do
  if [ ! -f "$SRC/$f" ]; then
    echo "ERROR: Missing $SRC/$f" >&2
    exit 1
  fi
  echo "" >> "$OUT"
  cat "$SRC/$f" >> "$OUT"
  echo "" >> "$OUT"
done

echo "Built $OUT ($(wc -l < "$OUT") lines, $(wc -c < "$OUT") bytes)"

# ─── Build lazy chunks ───────────────────────────────────────
mkdir -p "$CHUNKS_DIR"
# Note: chunks are rebuilt in-place (overwritten), no need to delete first

for entry in "${CHUNK_FILES[@]}"; do
  chunk_name="${entry%%:*}"
  src_file="${entry##*:}"

  if [ ! -f "$SRC/$src_file" ]; then
    echo "ERROR: Missing $SRC/$src_file" >&2
    exit 1
  fi

  chunk_out="$CHUNKS_DIR/$chunk_name.js"
  echo "/* IQcadence chunk: $chunk_name — lazy-loaded */" > "$chunk_out"
  echo "" >> "$chunk_out"
  cat "$SRC/$src_file" >> "$chunk_out"
  echo "" >> "$chunk_out"

  echo "  Chunk $chunk_name.js ($(wc -l < "$chunk_out") lines, $(wc -c < "$chunk_out") bytes)"
done

echo ""
echo "Core: $(wc -l < "$OUT") lines | Chunks: ${#CHUNK_FILES[@]} files in js/chunks/"

# ─── Minify if esbuild is available ──────────────────────────
if command -v esbuild &> /dev/null; then
  esbuild "$OUT" --minify --outfile="${OUT%.js}.min.js" --allow-overwrite
  echo "Minified ${OUT%.js}.min.js ($(wc -c < "${OUT%.js}.min.js") bytes)"
  for entry in "${CHUNK_FILES[@]}"; do
    chunk_name="${entry%%:*}"
    chunk_out="$CHUNKS_DIR/$chunk_name.js"
    esbuild "$chunk_out" --minify --outfile="$chunk_out" --allow-overwrite
  done
  echo "Minified all chunks"
else
  echo "NOTICE: esbuild not found — skipping minification. Install with: npm i -g esbuild"
fi
